# Generated by Django 6.0.5 on 2026-06-01 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAffairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Economy', 'Economy'), ('Science', 'Science'), ('Sports', 'Sports'), ('Politics', 'Politics')], default='National', max_length=30)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='current_affairs_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GovService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('documents_required', models.TextField()),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('process', models.TextField()),
                ('official_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=255)),
                ('post_name', models.CharField(max_length=255)),
                ('vacancies', models.IntegerField(default=1)),
                ('salary_range', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('last_date', models.DateField()),
                ('official_notification', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('notification_type', models.CharField(choices=[('Job', 'New Job Alert'), ('Exam', 'Exam Alert'), ('Scheme', 'Scheme Update'), ('Result', 'Result Released'), ('AdmitCard', 'Admit Card Available'), ('General', 'General Announcement')], default='General', max_length=20)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField()),
                ('download_link', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Farmers', 'Farmers'), ('Women', 'Women'), ('Students', 'Students'), ('Senior Citizens', 'Senior Citizens'), ('Startups', 'Startups'), ('Businesses', 'Businesses'), ('Healthcare', 'Healthcare'), ('General', 'General')], default='General', max_length=30)),
                ('eligibility_criteria', models.TextField(help_text='Detailed text or JSON criteria')),
                ('income_limit', models.DecimalField(decimal_places=2, default=300000.0, max_digits=12)),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=100)),
                ('gender_requirement', models.CharField(choices=[('Any', 'Any'), ('Male', 'Male'), ('Female', 'Female')], default='Any', max_length=10)),
                ('benefit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount in Rs.', max_digits=12)),
                ('documents_required', models.TextField()),
                ('application_process', models.TextField()),
                ('official_website', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('eligibility', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_date', models.DateField()),
                ('class_level', models.CharField(max_length=50)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('official_website', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('conducting_authority', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=100)),
                ('age_limit', models.IntegerField(default=30)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('important_dates', models.TextField(help_text='JSON format or list of key dates')),
                ('eligibility', models.TextField()),
                ('exam_pattern', models.TextField()),
                ('syllabus', models.TextField()),
                ('vacancy_count', models.IntegerField(default=0)),
                ('admit_card_link', models.URLField(blank=True, null=True)),
                ('result_link', models.URLField(blank=True, null=True)),
                ('official_website', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='portal.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('download_link', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='portal.exam')),
            ],
        ),
    ]
